<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "qbbootstrap"
 *
 * Auto generated by Extension Builder 2014-04-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Qbus Bootstrap',
	'description' => '',
	'category' => 'templates',
	'author' => 'Benjamin Franzke',
	'author_email' => 'bfr@qbus.de',
	'author_company' => 'Qbus',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.5',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
			'gridelements' => '2.0',
			'qbtools' => '1.4.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
